/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Time = bigint;
export interface Tournament {
  'id' : bigint,
  'startTime' : Time,
  'status' : TournamentStatus,
  'participants' : Array<Principal>,
  'maxSlots' : bigint,
  'name' : string,
  'gameMode' : string,
  'entryFee' : bigint,
  'filledSlots' : bigint,
  'prizePool' : bigint,
}
export type TournamentStatus = { 'upcoming' : null } |
  { 'live' : null } |
  { 'completed' : null };
export type TransactionType = { 'other' : null } |
  { 'tournament_fee' : null } |
  { 'deposit' : null } |
  { 'referral_reward' : null } |
  { 'withdrawal' : null };
export interface UserProfile {
  'referralCode' : string,
  'username' : string,
  'referredBy' : [] | [Principal],
  'gameUID' : string,
  'walletBalance' : bigint,
  'totalReferralEarnings' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WalletTransaction {
  'transactionType' : TransactionType,
  'description' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTournament' : ActorMethod<
    [string, bigint, bigint, bigint, Time, string],
    bigint
  >,
  'creditCoins' : ActorMethod<[Principal, bigint, string], undefined>,
  'depositCoins' : ActorMethod<[bigint, string], undefined>,
  'getAllProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getAllTournaments' : ActorMethod<[], Array<Tournament>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getTournamentDetails' : ActorMethod<[bigint], Tournament>,
  'getTransactions' : ActorMethod<[], Array<WalletTransaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWalletBalance' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinTournament' : ActorMethod<[bigint], undefined>,
  'register' : ActorMethod<[string, string, string, [] | [string]], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTournamentStatus' : ActorMethod<[bigint, TournamentStatus], undefined>,
  'withdrawCoins' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];