/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'referralCode' : IDL.Text,
  'username' : IDL.Text,
  'referredBy' : IDL.Opt(IDL.Principal),
  'gameUID' : IDL.Text,
  'walletBalance' : IDL.Nat,
  'totalReferralEarnings' : IDL.Nat,
});
export const TournamentStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'live' : IDL.Null,
  'completed' : IDL.Null,
});
export const Tournament = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'status' : TournamentStatus,
  'participants' : IDL.Vec(IDL.Principal),
  'maxSlots' : IDL.Nat,
  'name' : IDL.Text,
  'gameMode' : IDL.Text,
  'entryFee' : IDL.Nat,
  'filledSlots' : IDL.Nat,
  'prizePool' : IDL.Nat,
});
export const TransactionType = IDL.Variant({
  'other' : IDL.Null,
  'tournament_fee' : IDL.Null,
  'deposit' : IDL.Null,
  'referral_reward' : IDL.Null,
  'withdrawal' : IDL.Null,
});
export const WalletTransaction = IDL.Record({
  'transactionType' : TransactionType,
  'description' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTournament' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, Time, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'creditCoins' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
  'depositCoins' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getTournamentDetails' : IDL.Func([IDL.Nat], [Tournament], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(WalletTransaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinTournament' : IDL.Func([IDL.Nat], [], []),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTournamentStatus' : IDL.Func([IDL.Nat, TournamentStatus], [], []),
  'withdrawCoins' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'referralCode' : IDL.Text,
    'username' : IDL.Text,
    'referredBy' : IDL.Opt(IDL.Principal),
    'gameUID' : IDL.Text,
    'walletBalance' : IDL.Nat,
    'totalReferralEarnings' : IDL.Nat,
  });
  const TournamentStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'live' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Tournament = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'status' : TournamentStatus,
    'participants' : IDL.Vec(IDL.Principal),
    'maxSlots' : IDL.Nat,
    'name' : IDL.Text,
    'gameMode' : IDL.Text,
    'entryFee' : IDL.Nat,
    'filledSlots' : IDL.Nat,
    'prizePool' : IDL.Nat,
  });
  const TransactionType = IDL.Variant({
    'other' : IDL.Null,
    'tournament_fee' : IDL.Null,
    'deposit' : IDL.Null,
    'referral_reward' : IDL.Null,
    'withdrawal' : IDL.Null,
  });
  const WalletTransaction = IDL.Record({
    'transactionType' : TransactionType,
    'description' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTournament' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, Time, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'creditCoins' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
    'depositCoins' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'getTournamentDetails' : IDL.Func([IDL.Nat], [Tournament], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(WalletTransaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinTournament' : IDL.Func([IDL.Nat], [], []),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTournamentStatus' : IDL.Func([IDL.Nat, TournamentStatus], [], []),
    'withdrawCoins' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };